pimcore_data_hub:
    configurations:
        All:
            general:
                active: true
                type: graphql
                name: All
                description: ''
                group: ''
                sqlObjectCondition: ''
                modificationDate: 1655281055
                path: null
                createDate: 1655232430
            schema:
                queryEntities:
                    Product:
                        id: Product
                        name: Product
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: sku
                                        label: 'SKU Articolo'
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: legalTitle
                                        label: 'Legal Title'
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: category
                                        label: Category
                                        dataType: manyToManyObjectRelation
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: family
                                        label: Family
                                        dataType: manyToManyObjectRelation
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: subfamily
                                        label: Subfamily
                                        dataType: manyToManyObjectRelation
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: prova
                                        label: Prova
                                        dataType: classificationstore
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: allergens~cerealSelect
                                        label: 'Cereal and Glutens'
                                        dataType: select
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: allergens~crustaceans
                                        label: Crustaceans
                                        dataType: select
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: chemPhysChar~humidity
                                        label: Humidity
                                        dataType: quantityValue
                                    isOperator: false
                mutationEntities: {  }
                specialEntities:
                    document:
                        read: true
                        create: true
                        update: false
                        delete: false
                    document_folder:
                        read: true
                        create: false
                        update: false
                        delete: false
                    asset:
                        read: true
                        create: true
                        update: false
                        delete: false
                    asset_folder:
                        read: true
                        create: true
                        update: false
                        delete: false
                    asset_listing:
                        read: true
                        create: true
                        update: false
                        delete: false
                    object_folder:
                        read: true
                        create: true
                        update: false
                        delete: false
            security:
                method: datahub_apikey
                apikey: 8804faac7e6a019b592311150f5300d5
                skipPermissionCheck: true
                disableIntrospection: false
            workspaces:
                asset: {  }
                document: {  }
                object:
                    -
                        read: true
                        cpath: /
                        create: false
                        update: false
                        delete: false
                        id: extModel1589-1
            permissions:
                user:
                    -
                        id: 2
                        name: admin
                role: {  }
